name: cli_creator
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  args: ^2.6.0
  dcli: ^7.0.1
  process_run: ^1.2.2+1
  recase: ^4.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  creator: cli_creator


platforms:
  linux:
  macos:
  windows:
